
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LETRA_MINUS = 21;
  public static final int GUION = 4;
  public static final int PUNTO = 10;
  public static final int CADENA = 20;
  public static final int CARACTER_ESP = 23;
  public static final int SUMA = 13;
  public static final int LLA_IZQ = 8;
  public static final int LIN_VERTICAL = 11;
  public static final int LLA_DER = 9;
  public static final int PORCENTAJE = 15;
  public static final int CARACTER = 19;
  public static final int COMA = 6;
  public static final int NUMEROS = 22;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int ASTERISCO = 12;
  public static final int DOS_PTS = 3;
  public static final int INTEROGACION = 14;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 17;
  public static final int VIRGULILLA = 7;
  public static final int PUNTO_COMA = 16;
  public static final int LETRA_MAYUS = 18;
  public static final int PRIV_CONJ = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRIV_CONJ",
  "DOS_PTS",
  "GUION",
  "MAYOR",
  "COMA",
  "VIRGULILLA",
  "LLA_IZQ",
  "LLA_DER",
  "PUNTO",
  "LIN_VERTICAL",
  "ASTERISCO",
  "SUMA",
  "INTEROGACION",
  "PORCENTAJE",
  "PUNTO_COMA",
  "IDENTIFICADOR",
  "LETRA_MAYUS",
  "CARACTER",
  "CADENA",
  "LETRA_MINUS",
  "NUMEROS",
  "CARACTER_ESP"
  };
}

