/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1_py1_201906562;

import analizador.parser;
import analizador.scanner;
import java.io.BufferedWriter;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.nio.Buffer;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author henry
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    File fichero_actual = null;

    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_abrir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_guardarcomo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_editor = new javax.swing.JTextArea();
        lb_editor = new javax.swing.JLabel();
        btn_analizar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_abrir.setText("Abrir");
        btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrirActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_guardarcomo.setText("Guardar como");
        btn_guardarcomo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarcomoActionPerformed(evt);
            }
        });

        txt_editor.setColumns(20);
        txt_editor.setRows(5);
        jScrollPane1.setViewportView(txt_editor);

        lb_editor.setText("Editor");

        btn_analizar.setText("Analizar Entrada");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardarcomo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_editor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_analizar)
                        .addGap(35, 35, 35)
                        .addComponent(btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_editor)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_abrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_guardarcomo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_analizar)
                    .addComponent(btn_Limpiar))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(txt_editor);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            fichero_actual = fileChooser.getSelectedFile();
            String contenido = "";

            try {
                Scanner input = new Scanner(fichero_actual);
                while (input.hasNextLine()) {
                    contenido += input.nextLine() + "\n";

                }
                input.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
            txt_editor.setText(contenido);
        }
    }//GEN-LAST:event_btn_abrirActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        File file = fichero_actual;
        String text = txt_editor.getText();

        try (PrintWriter out = new PrintWriter(file, StandardCharsets.UTF_8)) {
            out.print(text);
            System.out.println("Se guardo el archivo con exito");

        } catch (Exception e) {
            e.printStackTrace();
        }

//        if (fichero_actual != null) {
//            
//            
//        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
        String entrada = txt_editor.getText();

        String content = "";
        int cont = 1;
        content += "<!doctype html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "     <meta charset=\"utf-8\">\n"
                + "     <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "     <title>\"\"\" + nombre + \"\"\"-errores</title>\n"
                + "     <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css \" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\n"
                + "</head>\n"
                + "<body style=\"background-color: #f0efe9;\"> "
                + "     <div class=\"text-center mb-5\">\n"
                + "         <h1 class=\"display-4 text-black\">REPORTE DE ERRORES</h1>    \n"
                + "     </div>\n"
                + "     <div class=\"container\">\n"
                + "         <div class=\"row\">\n"
                + "             <div class=\"col\">\n"
                + "                 <table class=\"table\">\n"
                + "                     <thead>\n"
                + "                         <tr>\n"
                + "                             <th scope=\"col\">#</th>\n"
                + "                             <th scope=\"col\">Tipo</th>\n"
                + "                             <th scope=\"col\">Mensaje</th>\n"
                + "                             <th scope=\"col\">Linea</th>\n"
                + "                             <th scope=\"col\">Columna</th>\n"
                + "                         </tr>\n"
                + "                     </thead>\n"
                + "                     <tbody class=\"table-group-divider\">";

        try {

            scanner scanner = new scanner(new java.io.StringReader(entrada));
            parser analizador = new parser(scanner);
            analizador.parse();
            System.out.println("ANALISIS TERMINADO");

            for (int i = 0; i < scanner.erroreslexicos.size(); i++) {
                content += "                     <tr>\n"
                        + "                         <td> " + cont + " </td>\n"
                        + "                         <td> " + scanner.erroreslexicos.get(i).getTipo() + " </td>\n"
                        + "                         <td> " + scanner.erroreslexicos.get(i).getDescripcion() + " </td>\n"
                        + "                         <td> " + scanner.erroreslexicos.get(i).getFila() + " </td>\n"
                        + "                         <td> " + scanner.erroreslexicos.get(i).getColumna() + " </td>\n"
                        + "                     </tr>\n";
            }

            for (int i = 0; i < analizador.erroressintacticos.size(); i++) {
                content += "                     <tr>\n"
                        + "                         <td> " + cont + " </td>\n"
                        + "                         <td> " + analizador.erroressintacticos.get(i).getTipo() + " </td>\n"
                        + "                         <td> " + analizador.erroressintacticos.get(i).getDescripcion() + " </td>\n"
                        + "                         <td> " + analizador.erroressintacticos.get(i).getFila() + " </td>\n"
                        + "                         <td> " + analizador.erroressintacticos.get(i).getColumna() + " </td>\n"
                        + "                     </tr>";
            }

            content += "</tbody>\n"
                    + "                </table>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "\n"
                    + "    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js\"\n"
                    + "        integrity=\"sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2\"\n"
                    + "        crossorigin=\"anonymous\"></script>\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>";

            if (scanner.erroreslexicos.isEmpty() && analizador.erroressintacticos.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se encontraron errores lexicos/sintacticos");
            } else {
                JOptionPane.showMessageDialog(null, "Se encontraron errores lexicos/sintacticos\n"
                        + "Generando reporte de errores ");
                Crear_ErroresHTML(content, "ERRORES_201906562\\", "Errores");

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_analizarActionPerformed

    private void Crear_ErroresHTML(String cadena, String carpeta, String nombre) {
        FileWriter fichero = null;
        PrintWriter escritor = null;
        try {
            fichero = new FileWriter(carpeta + nombre + ".html");
            escritor = new PrintWriter(fichero);
            escritor.println(cadena);
            escritor.close();
            fichero.close();
        } catch (Exception e) {
            System.out.println("error en generar html");
            e.printStackTrace();
        }
    }
    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        txt_editor.setText("");
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_guardarcomoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarcomoActionPerformed
        JFileChooser guardarcomo = new JFileChooser();
        guardarcomo.showSaveDialog(null);
        guardarcomo.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        File archivo = new File(guardarcomo.getSelectedFile()+ ".olc");
        
        try {
            BufferedWriter salida = new BufferedWriter(new FileWriter (archivo) ); 
            salida.write(txt_editor.getText());
            salida.close();
        } catch (Exception e) {
            System.out.println("Error al guardar");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_guardarcomoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_analizar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardarcomo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_editor;
    private javax.swing.JTextArea txt_editor;
    // End of variables declaration//GEN-END:variables
}
